---
- name: Create a libvirt VM from an image and assign it a static IP with cloud-init
  hosts: localhost
  gather_facts: no

  vars:
    vm_name: my_vm
    vm_image_path: /path/to/image.qcow2
    vm_network_name: default
    vm_ip_address: 192.168.122.100

  tasks:
    - name: Create the VM disk image
      command: qemu-img create -f qcow2 /var/lib/libvirt/images/{{ vm_name }}.qcow2 10G

    - name: Create the VM from the image
      command: virt-install --name {{ vm_name }} --memory 2048 --vcpus 2 --disk path={{ vm_image_path }},format=qcow2 --import --network network={{ vm_network_name }},model=virtio --noautoconsole

    - name: Create the VM from the image with cloud-init configuration
      virt_install:
        name: "{{ vm_name }}"
        memory: 2048
        vcpus: 2
        disk:
          - path: "{{ vm_image_path }}"
            format: qcow2
            boot_order: 1
        network:
          - network: "{{ vm_network_name }}"
            mac: "52:54:00:f0:f0:f0"
            model: virtio
        graphics:
          type: vnc
          listen: 0.0.0.0
        metadata:
            instance-id: "{{ vm_name }}"
            local-hostname: "{{ vm_name }}"

          userdata:
            #cloud-config
            hostname: "{{ vm_name }}"
            fqdn: "{{ vm_name }}.example.com"
            manage_etc_hosts: true

            users:
              - name: ansible
                ssh-authorized-keys:
                  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDZzJ9v5L3f7L6gj4zJYK6w+9X5rZn7yJ8hWzT6y5cR4Bb9XvLj4kxqZl1V8tVJQ7LlWmKjUOgHd8t+oY9s3ZzDhFmXxvzKfYrQdGpJiF5aFbTtKpUHsWwqM4RbNn7Pv6+e8kZV+oW5p1eXnHgjOyIuQxqjGvCkRmJ3cPdG9wB6LrUaTt3Ys7yBhHlMgN6iDfKdRrSbIaWzSdE4xw1eNQXOy3u7V5c+YfCz7PnNlUJmLZyq9hGcV4mKs8pMvSxuOoUjTtFgCpXrRiFkAe5xw7Dv9qIbWuUOa8M1mZzCjgB+JhLsV4lQoIuE1yfZzYsJ8iXgMnRi6hS5lNcHkPbMgKQ3nBwDp/ ansible@ansible"
                sudo: ALL=(ALL) NOPASSWD:ALL

            network:
              version: 2
              ethernets:
                eth0:
                  dhcp4: no
                  addresses:
                    - "{{ vm_ip_address }}/24"
                  gateway4: "192.168.122.1"
                    nameservers:
                    addresses:
                      - "8.8.8.8"
                      - "8.8.4.4"
    - name: Wait for the VM to boot up
      wait_for:
        host: "{{ vm_ip_address }}"
        port: 22
        delay: 10
        timeout: 300

    - name: Add the static IP address to the VM's cloud-init configuration file
      lineinfile:
        path: /var/lib/libvirt/dnsmasq/default.addnhosts
        line: "{{ vm_ip_address }} {{ vm_name }}"

    - name: Start the VM
      command: virsh start {{ vm_name }}
