project:
  type: website

website:
  title: "Rancher-Ops Docs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: notes.qmd
        text: Notes
format:
  html:
    theme: darkly
    css: styles.css
    toc: true



